apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVVHTkVSQzZYU0ZVUDRZNkY=
  AWS_SECRET_ACCESS_KEY: Qzl4c1Q3aTVWbXhKZU81MU1FbndQNml1Sk81Yms2NXg0ajk4NGRNbg== # Base64 encoded
